### ISSUE TITLE
finish the Users component

### ISSUE THREAD

**Issue by fazo96** [fazo96/ipfs-boards#22]
This page has:
- [x] a list of users that have been discovered
- [ ] a search box to find people

**Comment by fazo96** [comment]
Search box is harder than expected:

- requires an in memory dictionary (username to userid) to filter through

**Comment by jbenet** [comment]
could have an autocomplete system that works over a search index which itself is made up of ipfs objects. look into @krl's great work on:

- https://github.com/krl/aolog
- https://github.com/krl/uplog
- https://github.com/ipfs/ipfs-geoip

**Comment by fazo96** [comment]
@jbenet Thanks a lot! [aolog](https://github.com/krl/aolog) looks expecially interesting and very useful to solve this problem.
