### ISSUE TITLE
Write hybrid HTTP-Websocket backend

### ISSUE THREAD

**Issue by fazo96** [fazo96/ipfs-boards#25]

**Comment by jbenet** [comment]
We would like to add websockets to go-ipfs -- for both api and for
connecting to nodes. May be worth adding it to js-libp2p as a transport
soon cc @diasdavid

**Comment by fazo96** [comment]
websockets to go-ipfs would make it a lot nicer to communicate high bandwidth of data (it currently is horrible lol) and by backend I mean a real server application that has some added logic (not just an ipfs node) and automatically gathers data from users to make sure it's not lost. 

The ultimate idea is, for browsers that can't or won't run js-ipfs, to talk to a backend via websockets or http. This could have some advantages like:

- highly reduced bandwidth for people that have data caps
- highly reduced cpu usage / processing power needed because all the lifting is done on the backend

**Comment by diasdavid** [comment]
> May be worth adding it to js-libp2p as a transport. soon cc @diasdavid

We prefer WebRTC over WebSockets (which pretty much has the same data interface), we would be able to dial to IPFS nodes behind NATs from the browser (or that is what I've been giving priority in libp2p)

**Comment by fazo96** [comment]
@diasdavid what I'd like for this application is something more efficient than HTTP to talk to go-ipfs, doesn't matter what it is just that it is more efficient and well compatibile. As far as js-libp2p from my limited understanding I think WebRTC is better than WebSockets because it's built with peer to peer in mind.

Still, HTTP works, so it's not a priority to build a replacement

**Comment by diasdavid** [comment]
Now I understand, you are looking to a WebSockets API, not a WebSockets transport for libp2p. 

That should be doable and in small window of time (if someone has the bandwidth, of course), @whyrusleeping made the cli-httpAPI-commands very decoupled :)

**Comment by jbenet** [comment]
> We prefer WebRTC over WebSockets (which pretty much has the same data interface)

Tons of sysyems do not speak WebRTC but do speak WebSockets. In the end, it's just another transport. Also we'll need this to help browsers connect to the rest of the network (WebRTC has to bootstrap through introducers-- that can happen over other transports-- WebSockets and HTTP LongPolling or whatever)

> you are looking to a WebSockets API

ah, yeah we should make that too.

we should write a way to layer the golang `cmds` library over a raw socket for clean RPC. people want it to work over unix domain sockets too.
