### ISSUE TITLE
Figure out an alert and notification system

### ISSUE THREAD

**Issue by fazo96** [fazo96/ipfs-boards#27]

**Comment by jbenet** [comment]
Pub sub will be very useful here.

We could probably bite the bullet and try a preliminary "very alpha"
version to try out for you.

**Comment by fazo96** [comment]
Yeah that could be veeery useful! Ihad to implement IPNS polling but on 0.3 it works very bad because the response times from go-ipfs are huge. I also have another problem currently which is user discovery, it works more or less but it's not good enough, also I need to resolve _every single_ IPNS address of every possible user to get his data and that's very slow atm. I think it's probably going to be a lot better on 0.4 but I won't migrate my API [until the files api is in place in js-ipfs-api](https://github.com/ipfs/js-ipfs-api/pull/74)

**Comment by jbenet** [comment]
yeah pub/sub will do it. I'll lift it up in my priorities.

**Comment by fazo96** [comment]
The best thing would be the ability to listen to _ipns update_ events, of _every node_. I'm scared about scalability of this approach though... what if there's a million nodes with hundreds of them updating every few seconds?
