### ISSUE TITLE
Consistent ES2015 usage

### ISSUE THREAD

**Issue by fazo96** [fazo96/ipfs-boards#39]
- [ ] use classes for react components
- [ ] use ES6 `import` instead of `require`
- [ ] use `function name(){}` instead of `name: function(){}` when applicable
- [ ] use react stateless components when applicable
- [ ] use promises instead of horrible callbacks (solves callback hell)
- [ ] investigate using generators or async/await

**Comment by Dignifiedquire** [comment]
Also very nice: Stateless components: https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components

**Comment by fazo96** [comment]
@Dignifiedquire thanks! that's very nice

**Comment by kustomzone** [comment]
Hi, nice app fazo. I've got it basically working on windows (not sure if it required mount) but only on Chrome 40+ (FF gives "let is a reserved identifier", and Maxthon "const while in strict mode"). Is there a toggle somewhere (babel?) for backwards compatibility mode?

**Comment by fazo96** [comment]
Hi! Thanks a lot for trying the app!

I think it only works on chromium because I've been developing it there: we're still at a very experimental stage and basic features are still missing so I'm not worrying about compatibility. Also I plan to release a desktop version of the app using electron, which is based on chromium. I briefly tried it on firefox and it looked like it worked fine though.

The app is precompiled by webpack with babel so that it works on all modern browsers, although there's probably some files I should compile that I didn't catch. Did you try from the URL in the readme or from source?

I'll open a new issue about browser compatibility so that we can discuss there!

**Comment by kustomzone** [comment]
Hi, 

Yes, babel (eslint) for some reason is inserting 'use strict'  ..but without the ending semicolon.
It's function /* 18 */ in my case.
/***/ function(module, exports) {
	'use strict'

I've been trying different things without success (eslintrc "strict" with never/global/function) but i'm curious if yours is same?

ps. built fine without gulp, nicely done!
