### ISSUE TITLE
support building on Windows

### ISSUE THREAD

**Issue by fazo96** [fazo96/ipfs-boards#66]
continues discussion in #63 

Current known problems:
- ~~paths in `webpack.config.js` use forward slashes instead of being normalized for the OS~~ guess webpack was smart enough

**Comment by fazo96** [comment]
Looks like webpack works, but there is an issue with the babel runtime:

```

ERROR in ./webapp/pages/settings.jsx
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/json/stringify' in C:\Users\Fazo\Documents\Git\ipfs-boards\webapp\pages
 @ ./webapp/pages/settings.jsx 3:17-64

ERROR in ./lib/boards-api.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/json/stringify' in C:\Users\Fazo\Documents\Git\ipfs-boards\lib
 @ ./lib/boards-api.js 3:17-64

ERROR in ./~/ipfs-api/~/wreck/lib/index.js
Module not found: Error: Cannot resolve module 'https-browserify' in C:\Users\Fazo\Documents\Git\ipfs-boards\node_modules\ipfs-api\node_modules\wreck\lib
 @ ./~/ipfs-api/~/wreck/lib/index.js 8:14-30

ERROR in 1.app.js from UglifyJs
Unexpected token: operator (>) [./~/ipfs-api/src/cmd-helpers.js:4,0]
```

@kustomzone do you know anything about this error?

**Comment by kustomzone** [comment]
Yes, i've only had the last one to resolve, but there are other 'use static' (missing semicolons) further in the code and i believe that's what's causing it. As i'm new to babel so been googling all weekend only to discover it's not easily fixed. Weird.

Is there any difference between node module 'babel-eslint' or 'eslint-plugin-babel' or just 'eslint'? I was trying to swap one for another to try to resolve, but they may be identical. Updating other modules hasn't resolved. So it might just be a bug with babel as you say. Hmm.

**Comment by kustomzone** [comment]
Yes, the forward slashes is unresolved too. Been googling but haven't found any discussion about that yet. There's an empty quote in the chunking code which could have a unassigned reference..

a.src=t.p+""+e+".app.js"
               ^^^
..but the other (unchunked) assets are also affected, so i'm not sure whether path.resolve or another option is better, but i've read through the docs and tried without success the more obvious ones.

**Comment by fazo96** [comment]
> Is there any difference between node module 'babel-eslint' or 'eslint-plugin-babel' or just 'eslint'?

Yes, I'm afraid there's a big difference:

- babel-eslint I think provides babel with the ability to lint the code with eslint before compiling
- eslint is a linter, a tool that checks wether your code respects given rules and is correct
- eslint-plugin-babel I think gives eslint the ability to use babel to undestand ES2015

I think the real problem is that something is wrong with babel on windows. I'll investigate a little about it as soon as I have time

**Comment by fazo96** [comment]
Created a branch to support building on windows.

Here it is: https://github.com/fazo96/ipfs-boards/tree/windows-build

I got webpack to compile without errors! But something is wrong with the path detection regexes, I think babel is ran on modules where it shouldn't run, breaking the build: in the browser, it only works partially.

**Comment by kustomzone** [comment]
Thanks! The build error has gone now. Still confused about the paths with IPFS.
If i add.. 'publicPath: 'dist' ..to webpack.config then i get an index.html with the correct tag..
<script src="dist\app.js"></script></body>
..when i load the IPFS hash address i get the file list with dist folder with backslashes which load normally. But when i click on index.html i get 404 on ... http://localhost:8080/ipfs/###/dist/app.js
So maybe the IPFS server is converting the backslashes to url-formatted forwardslashes. Or the browser is, because my browser seems to do that as well. Before i was bootstrapping with 'dist%5C' somewhere, but now i can't remember where, and it only worked for app.js and not the other links (svg, ttf, chunks, etc)

I'm on win7 and have the latest npm (3.5.3) and node (5.2.0).

**Comment by fazo96** [comment]
@kustomzone I just realized I haven't tried loading the app from IPFS, only through the webpack development server. I'll try as soon as I can and fix that too :+1:
