### ISSUE TITLE
Write shell scripts or cli application to ease development

### ISSUE THREAD

**Issue by fazo96** [fazo96/ipfs-boards#7]
- [ ] tool to create a sample profile
- [x] [tool to publish profile](https://github.com/fazo96/ipfs-boards/blob/master/publish_profile.sh)
- [x] [tool to serve the webapp](https://github.com/fazo96/ipfs-boards/blob/master/HACKING.md)
- [x] [tool to ship the webapp over IPFS](https://github.com/fazo96/ipfs-boards/blob/master/upload_webapp_on_ipfs.sh)
- [x] [tool to quickly set CORS on go-ipfs](https://github.com/fazo96/ipfs-boards/blob/master/ipfs_daemon_set_cors.sh)

**Comment by harlantwood** [comment]
If you don't have a node module in mind already for handling command line, check out https://www.npmjs.com/package/commander -- it's been a pleasure to work with for me.

**Comment by harlantwood** [comment]
Which part of shipping the webapp is hard?  You may be interested in https://github.com/diasdavid/ipscend btw.

**Comment by fazo96** [comment]
@harlantwood I don't remember what was hard about shopping the web app over ipfs, few days ago I wrote a shell script to do it. Also gulp is being used to serve the app. This issue got a little left behind as I worked on other things, should probably do some cleaning up :+1:
