### ISSUE TITLE
Link IPNS ID to username

### ISSUE THREAD

**Issue by fazo96** [fazo96/ipfs-boards#76]
The problem is: how can I find a user if I don't know his Node ID?

I think we should have a system that resolves names to IPNS IDs, of course it has to be centralized so users can register their names, but then the user can choose which service to use in his application.

**EDIT:** my opinion was updated, see below

**Comment by jbenet** [comment]
Identity is a big, big topic. i've a datastructure in mind for this, similar to (and for use with) POST. 

i dont think we need a centralized though, we just need byzantine consensus, and even at that we only need federated bizantine consensus (stellat). 

i suggest do something simple for now, like email or OAuth, but leave room for upgrading this

**Comment by fazo96** [comment]
For now the plan is:

- a user is identified by his node ID
- a user will be able to include "proofs" into his profile, to prove that he also has access to social media accounts like twitter, facebook. Just like keybase.io does it.

The real issues are:

- __A user wants to be able to access his identity from multiple devices__: looks like you have big plans for this, so I won't try to solve this problem on my own :+1: maybe just a workaround such as istructions to transfer the keys to another machine
- associating a name such as `fazo96` or `jbenet` to an IPNS name or an identity. I thought about an external centralized service to register names, but I probably won't work on this since it's too much hassle for what it's worth

Thanks for your input :+1:
