### ISSUE TITLE
Any planned refresh?

### ISSUE THREAD

**Issue by daviddias** [fazo96/ipfs-boards#97]
Hi @fazo96, do you have any plans for updating this app to the latest module versions? Would be sweet to see it working with latest IPFS :)

**Comment by fazo96** [comment]
hey @diasdavid thanks for the interest :)

I am working on a brand new prototype using the excellent orbit-db. There's an `experimental` branch but nothing works yet. I'll update all the documentation and publish it on IPFS as soon as it works
